permalink: /:year:month:day/:title
url: #Your url here
baseurl:

# variables
name: HERNANEX3
description: Coding for fun and profit
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
highlighter: rouge
markdown: kramdown
